DROP DATABASE IF EXISTS `db2019`;
CREATE DATABASE `db2019`;

USE `db2019`;
DROP TABLE IF EXISTS `payment`;
CREATE TABLE `payment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `serial` varchar(64) NOT NULL DEFAULT '' COMMENT '序号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8 COMMENT='支付表';